### ISSUE TITLE
Logic difference between navButton and progress navigation

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1018]
From https://github.com/cfpb/hmda-platform/issues/1477.

Just wanted to make sure to get this into an issue so we can think about different ways of handling this in the UI. _The current way may be fine._

I think we have some mismatched logic between how the nav gets rendered and how the "next" buttons at the bottom get rendered.

When this weird state from https://github.com/cfpb/hmda-platform/issues/1477 happens you'll see that the "submission" link in the nav is not available, which is good given the status, but, they can still get there by using the "next" buttons. It seems like that button shouldn't be available either and we should render an error instead because we have a state that doesn't match the edit count.

But ... maybe what is happening is ok? There's an error message and the signature is disabled so maybe we're ok?

**Comment by wpears** [comment]
Yeah, I think it's probably worthwhile to factor out the Nav logic into `utils` and reuse that for both cases.

This is a strange case, because while I want the UI to function well in this case, really this should *never* happen. I'd be wary of adding too much here that makes things crufty in the future, because once the backend issue is fixed, we shouldn't encounter this anymore.
