### ISSUE TITLE
Message to users without an associated LEI

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-ui#1114]
**Background:** We expect that a significant number of 2017 users will have accounts in v2 Keycloak that are not associated with any LEI (~ currently no known LEI for about 600 2017 FIs). The users will be able to log into beta, but will not be associated with an institution. We need the UI to message what we want them to do. 

**To-do:** 
- confirm that the auth token passed upon login contains LEI information, and that the lack of LEI in the token can be used to trigger a message in the UI
- provide instructions to user on next steps in the UI

Assuming that the token can be used to determine when LEI is missing, the message should be:

"In order to access the HMDA Platform, your institution must have a Legal Entity Identifier (LEI). In order to provide your institution's LEI, please access [this form](https://hmdahelp.consumerfinance.gov/accounthelp/) and enter the necessary information, **including** your HMDA Platform account email address in the "Additional comments" text box. We will apply the update to your account, please check back 2 business days after submitting your information." 

ETA the salesforce web form link. 

@awolfe76 @chynnakeys @MattPerrine feel free to edit for clarity.

**Comment by keileyo** [comment]
@awolfe76 I think we want to update this message a tiny bit. I added the second sentence to the message below to account for people who may see this message + the ability to file for other institutions that do have an LEI.

"In order to access the HMDA Platform, your institution must have a Legal Entity Identifier (LEI). It appears that at least one institution associated with your account does not have an LEI on record.  In order to provide your institution's LEI, please access this form and enter the necessary information, including your HMDA Platform account email address in the "Additional comments" text box. We will apply the update to your account, please check back 2 business days after submitting your information."

Edit: the link to the webform is https://hmdahelp.consumerfinance.gov/accounthelp/

**Comment by awolfe76** [comment]
_These are some initial thoughts on different scenarios._

There are a few cases to work through here. And these can be done in steps.
_The `lei` and `institutions` below are Keycloak attributes._

### Step 1 (a generic catch all)

#### No `lei` found at all

The basic first step is to provide a generic message, like above, saying that we don't have a `lei` for their 2017 institution and that it needs to be added. This does not provide an details back to the user, but in most cases should be enough to get them started (their login with their email domain should point them in the right direction).

Doing this missed the case of "one or more `lei`s and a greater number of `institutions`" (in step 2 below), but this is ok for now. If we don't find any `lei`s, just tell them.

### Step 2

#### One or more `lei`s but no `institutions`

This would be a new registration in for 2018 filing and is ok.

#### One or more `lei`s and an equal number of `institutions`

This would have come from our migration of data and is also ok. A user can not register twice, so our migrated data had good matches in this case.

#### One or more `lei`s and a greater number of `institutions`

In this case we were unable to match the previous filing year institution(s) to one or more `lei`(s). We can go ahead and call the v2 API, `/institutions/<lei>`, and, if successful, remove the `institutionId2017` from that response from the list of `institutions` from the keycloak token because we'll know its good. After this "clean up" we'll have the list of `institutions` without an `lei` (that we know of). Then, we'll have to query the [`v1` institution API (by id, `/institutions/<institutionID>`)](https://github.com/cfpb/hmda-platform/blob/master/docs/v1/public-api.md#search) in order to show a better warning/error message per `institution` without a matching `lei`. 

#### No `lei` and at least one `institutions`

If there is no `lei` we know something is wrong. We'll have to follow the steps above in order to render a better warning/error. We just don't have to make the initial v2 API call (again, there's no `lei` to make the call with).

#### No `lei` and no `institutions`

This case should not happen.

#### One or more `lei`s and a lesser number of `institutions`

This is ok. This is likely a good match on the migration and then a user requested a new institution later, based on the `lei`.

**Comment by awolfe76** [comment]
Closed by #1155
