### ISSUE TITLE
Refactor edit components

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#157]
Do a small refactor on the the edit components to simplify logic required to render the unique types of edits. This could all be fixed in one PR or a few ... small PR's are great! 😄 
- syntactical and validity edits can remain as one component
  - it would be useful to rename that components to something like `EditsSyntaxValidity.jsx`
  - be sure to continue to allow sorting by row and by edit
- create a `EditsQuality.jsx` to handle the only quality edits
  - quality edits only render one checkbox, verify all, for each edit ... not for each record (see #156)
  - integrate Q029 into the quality edits
    - Q029 fits the "verify all" pattern
  - be sure to continue to allow sorting by row and by edit
- keep the `EditsQ595.jsx`
  - but modify it to have a checkbox instead of the radio buttons _(this isn't necessary but may be more obvious)_
    - the verification text (in the table header) should read something like "check if you have an office in this msa"
- modify `EditsMacro.jsx` to render a `<select>` instead of a `<textarea>`
  - we don't have the `<options>` yet, they are unique per macro edit, but we can create a placeholder

This will likely also change, if not remove the need for,:
- `EditsDetail.jsx`
- `EditsDetailRow.jsx`
- `EditsGrouped.jsx`
- maybe more

**Comment by wpears** [comment]
Seems to me that Q595 could actually be a _macro_ edit. Doesn't have to be, but that's the term we're generally using for edits that require knowledge of the system outside of a single row (since MSAs are only shown once, no matter how many rows fail the edit check). Having Q595 by itself seems a bit odd to me, like something is mixed up in the information architecture. Perhaps it warrants it, but in that case we should think harder about what exactly we want in the separate class (is it only q595? Other macro edits with ad hoc checkbox meanings?)

**Comment by lesgou** [comment]
Q595 <> a macro edit because while it looks at the entire file, the check does not result in 1 response (i.e., certain type of loans > 10%). The result is a list of msa/md's in which the filer has to go through and verify each line individually. 

A macro edit would have one response per edit, whereas Q595 has multiple responses.

**Comment by wpears** [comment]
Closing in favor of #164 and #165
