### ISSUE TITLE
Start and stop validation

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#16]
In the Pilot "summary and findings" document users talk about wanting the ability to start and stop the process. Its also mentioned with the idea of multiple users which makes me think they would like to run the checks but allow someone else to sign at the end.

Questions:
- Would we have a "pause" button in the UI?
- Rather than a "pause" button, could this just be done at certain points? (We save progress when syntax is complete, when validity is complete, when quality is complete, etc. This would mean that they would have to wait until at least a certain point.)
- Would it be easier to track if only done at certain points? Seems like the UI might be easier, not sure about the backend.

@debseidner @wpears @benguhin

**Comment by benguhin** [comment]
I'm a fan of having a button that says "Save and continue later," which implies that (a) you can continue later and (b) you don't have to keep pressing the button in order to save your work as you go. Here's an example from our [complaint form prototype](https://github.cfpb.gov/pages/consumer-response/021-consolidated-form/021%20prototype%20v0.50/company-information.html): 
![screen shot 2016-02-08 at 12 52 42 pm](https://cloud.githubusercontent.com/assets/6953063/12894110/df9fea0a-ce62-11e5-97dd-74c7ece42d1f.png)

Additionally, you could follow the google docs pattern of including a line of text (e.g., "All changes saved in Drive") that updates the user about whether it's safe to close the browser window. I don't think that's necessary for this sort of application, though.

![screen shot 2016-02-08 at 12 49 00 pm](https://cloud.githubusercontent.com/assets/6953063/12894040/85b2d408-ce62-11e5-8657-b860e82750e0.png)

**Comment by debseidner** [comment]
I think what people are looking for is the save and continue aspect Ben mentions. They want to stop in the middle of working on the quality edits to take a break - as takes a lot of work to research - or to stop and go ask a colleague about what the response should be for a macro edit. Typically the person answering the questions is not the loan officer and that person might need to go check with a loan officer on the issue. They don't want to have to go all the way through the quality and macro quality edits without the ability to stop.

I think with the multiple users, yes there is probably a different person that will sign - Chief Risk Officer, Chief Financial Officer, Chief Compliance Officer but the commentary from the Pilot users is more about having multiple compliance departments responsible for different types of loans across the country and wanting the ability to check the full file with different compliance officers logging in to answer the errors that pertain to their specific loans. The way Pilot was designed, they would all have to check their loans on their own, which won't take into account the macro edits for the full file,  or one person would have to run the file through the Pilot system, get the edit report and then download it for all the compliance officers around the country to comment in paper, spreadsheet, or email about their particular errors so that the one compliance officer can then rerun the file and go back and key in all of their responses.

**Comment by debseidner** [comment]
also would caution against saving any information for quality and macro quality edits until the syntactical and validity edits are cleared as the values for those edits might change with the fix that needs to be done to clear the syntactical and validity edits.

**Comment by awolfe76** [comment]
There will be certain, pre-determined, points where data will be persisted. For example:
- upload complete
- parsing complete
- syntax complete
- validity complete

More to points to come later, but these points will allow users to leave the application and return to that   point at a later time.
