### ISSUE TITLE
Fix docker-compose

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#202]
https://github.com/cfpb/hmda-platform-ui/pull/201 was to get the cluster deployment working. But it broke the docker-compose setup.

For now, to run docker-compose locally, you have to manually update the https://github.com/cfpb/hmda-platform-ui/blob/968f5635a85274a218c08b34ee5247979e3c07a2/nginx/nginx.conf#L13 to use port `8080` instead of `10003`.

This issue may require changes to the [platform](https://github.com/cfpb/hmda-platform) repo too.

**Comment by awolfe76** [comment]
Best answer here maybe to have back-end update configuration to use port `10003` instead of `8080`, leaving the `nginx.conf` as it is.

**Comment by awolfe76** [comment]
@jmarin @hkeeler what do you think about updating the back-config and then doing `EXPOSE 10003` in the dockerfile? I could recreate this issue in the platform repo if so.

**Comment by hkeeler** [comment]
@awolfe76 I agree.  Due to Nginx's static configuration, and the differences in how service discovery works in Compose vs our internal setup, the only _simple_ fix here is to make the container port and Docker host port be the same value (in this case `10003`) for any Nginx `upsteam`s.  And yes, the cleanest way to do this is to update [`hmda-platform/Dockerfile`](https://github.com/cfpb/hmda-platform/blob/master/Dockerfile#L18) to `EXPOSE 10003`.

Looks like we came to that same conclusion for grasshopper (see [`grasshopper/docker-compose-common.yml`](https://github.com/cfpb/grasshopper/blob/master/docker-compose-common.yml#L4))...which should also be updated to reflect the very similar change made to [`grasshopper-ui/nginx/nginx.conf`](https://github.com/cfpb/grasshopper-ui/blob/master/nginx/nginx.conf#L19).

@awolfe76, feel free to create those issues.  I think you can close this one out, as I don't think there should be any changes to this repo as part of this.

**Comment by wpears** [comment]
Hah, perhaps I should have read this before pushing https://github.com/cfpb/hmda-platform-ui/pull/203, which I think is actually a cleaner approach as it separates the dev setup from deploy.

Imagine if/when the marathon service port changes, we'd have to update code both in this project and in hmda-platform to keep everything in sync. With the code in #203, you just update the envvar in Jenkins.

**Comment by awolfe76** [comment]
I agree @wpears. Nice solution!

But, I think you just merged the same change in [grasshopper](https://github.com/cfpb/grasshopper/pull/220) that @hkeeler made on [platform](https://github.com/cfpb/hmda-platform/pull/536). Should we revert the grasshopper change and apply the #203 solution there as well?

I think an added benefit is that we should be able to inject the jenkins variable into the marathon scripts as well, removing the chance that they get out of sync. Would save us from having to update the marathon script and the jenkins job. Jenkins would be the place that held the ports. Once change there are we're up and running. _I think those are the only places that would matter._

Would be good to try that jenkins build too, before merging #203.

**Comment by wpears** [comment]
Yep, should probably revert that grasshopper change ;) I was thinking that it was somewhat more static, but really the same logic applies here as there.

wrt the marathon script, it's not quiiiite so nice because you'd actually want the the service port from `hmda-platform` not `hmda-platform-ui` (since that's the thing you're interacting with). I have some ideas about this that aren't too hacky that I'll implement now, then I'll point jenkins to the branch from #203 and see what happens

**Comment by awolfe76** [comment]
Yeah, you're right. I had created an issue a few days ago - [GHE]/HMDA-Operations/hmda-devops/issues/122 - talking about a _possible_ issue with ports in the future. Was hoping that all of this in fixed that in some way but no need to go there yet.

**Comment by awolfe76** [comment]
Closing. #203 fixed this.
