### ISSUE TITLE
Clarify app state / what are the different app checkpoints?

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#25]
Generally, these checkpoints will be when user input is required or an error has been found. Suggestions are as follows:
- Upload a file (first visit or upload failed)
- Review syntax/validity errors (if encountered)
- Justify quality/macro errors (if encountered)
- Sign and submit
- View submission

**Comment by awolfe76** [comment]
**Edited to add @debseidner suggestions**

Should we include a few more? 
- Upload a file (first visit or upload failed)
- File parsed
- End of syntactical checks
- End of validity checks
- End of quality checks
- If quality errors, each justification
- End of macro checks
- If macro errors, each justification
- IRS
- **IRS each comment on branch locations**
- Sign and submit
- View submission
- **Full audit trail**

Pilot had syntactical and validity combined and quality and macro combined. I split them above, curious if others think that would be more useful to provide more stopping points. Seems like it benefits both us and the filers to have more stopping points, allowing for smaller failures (I know, failures won't happen).

After talking with @debseidner, each justification should be a point as well. Some of these may require research and time away from the app. And each justification is also a UI interaction, so that makes those points a little easier to manage as well. We just need to make an API call to the backend each time.

**Comment by debseidner** [comment]
Those all sound good. Couple more:
-  We may also need one for branch updates depending on how we structure the IRS and whether we want to allow institutions to comment on where their branch locations are. 
-  We might also want to persist the full edit report - all the errors, responses to answers - so banks have a way to download that for their files. Today they have a paper copy of the report + handwritten notes on it with their responses but they would lose this ability with an online system.

**Comment by awolfe76** [comment]
@debseidner @wpears 

After talking Friday, I think all of the points still apply, but mostly for the backend in order to restart processing from a certain point, in case of a system error.

For the front-end, assuming we'll run all checks on an upload, we care about:
- knowing if syntactical and validity passed/failed
  - to show justification UI for quality and macro, these can't be done until syntactical and validity have passed
- quality and macro processed (with errors)
  - these checks must also be complete, and have errors, to show the justification UI
- saving after each quality and macro justification
  - allows filers to close browser to research and return later with progress saved
- all checks passed
  - in order to show the signature is required
- process complete
  - in order to provide full audit

**Comment by debseidner** [comment]
@awolfe76 I agree on all of the above. Just not sure what "all checks passed" is and "full audit". Can you clarify what you mean for both? By all checks passed, is it passed for quality when you have verified all and macro when you have verified and included a reason? Just want to make sure those are considered "passed". Is the full audit something like the IRS or a summary of the filing?

**Comment by awolfe76** [comment]
For "all checks passed", yes, I meant everything has passed or been verified. I'm assuming that is the only way they can get to the signature page, right?

For "full audit", I was thinking of the complete edit report, including multiple submissions if there were more than one. But I also think IRS and summary come at that same point.

**Comment by awolfe76** [comment]
Going to close this for now. Future issues for components will add more information around this and this issue can be referenced later.
