### ISSUE TITLE
Create "static" home page

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#278]
Our application should have a "static" home page when someone first comes to the application.

Possible content:
- FAQs (#277)
- header (#230)
  - login
  - ffiec logo
  - navigation (TBD)
- footer (#231)
- other messages we need (alert during filing period for example)
- links to docs (API, reg, help desk, other guides, etc)

**Comment by awolfe76** [comment]
@wpears @hkeeler 

This page should allow for authenticated and unauthenticated users. When they first come into the app, not authenticated yet, at `/` they should see a page that would have some information about HMDA, some FAQs, some basic navigation, and login link which would take them to the keycloak login page. If they are authenticated a few changes could happen, login becomes logout, and maybe a few other things.

I'm not sure what needs to be done to make that happen. Should we create issues here or the auth repo or both?

**Comment by wpears** [comment]
Yeah so right now, if a `user` isn't found in the state, the user is redirected to the signin page. I'd say we should leave this automatic behavior on everything except the homepage, but the fix for your usecase is just a matter of preventing the redirect on the homepage
https://github.com/cfpb/hmda-platform-ui/blob/master/src/js/redirect.js#L5
So that'd become `if(location.pathname === '/' || location.pathname === '/oidc-callback') return`
