### ISSUE TITLE
Home page content

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#512]
We might want to highlight the steps required to complete the process:

1. Register/Login
1. Select your institution
1. Upload your file
1. Fix syntactical and validity if they exist
1. Verify quality
1. Verify macro
1. Review the summary and sign

**Comment by designlanguage** [comment]
There's a lot of content on the homepage currently that doesn't seem relevant once you're logged in. I'm thinking the content that is relevant can probably be incorporated onto the institutions page, removing a logged-in homepage, but I'll work on some pencil wireframes to see if that can work.

I think providing context for what they'll need to do makes sense. I'm not sure if it needs to be in list form though.

**Comment by designlanguage** [comment]
@awolfe76 @wpears -

I marked up the current logged in home page content. Some questions from that exercise:
* Can we detect if a user has an incompatible browser and show a notification/error in that case?
* Would a logged-in user want/need the file format verification tool prominently shown? Would this be more helpful for a logged-out user?
* Can the paperwork reduction act be a link or shown less prominently?

![screen shot 2017-05-15 at 11 19 59 am](https://cloud.githubusercontent.com/assets/10562544/26067709/1307ac94-3969-11e7-8d33-422cff714719.png)

And here's (roughly) how we might consolidate the logged in home and institutions page. A few thoughts/questions:
* Wondering about having the filing deadline in the header in place of the Home/Institutions menu, especially for the first year, but maybe that's too naggy?
* I'm thinking "Refile" should be a regular link rather than a button equally prominent to "View filing". "Refile" will also be actionable within the filing and it seems that the main purpose of this page is to get into the filing.
* Hoping we can cut off the number of previous submissions so it's an expandable when the list gets long.
* Are there account pages separate from the logged in page? Is there any info a user would want/need from a page like that?
* Text about multiple institutions / filers can appear below the first institution.
* Text about the process/steps can appear along side the institution(s).
* All resources can be listed in the footer. It would be preferable if the links were descriptive enough not to require headings.

![wireframe](https://cloud.githubusercontent.com/assets/10562544/26067824/65af260c-3969-11e7-9f80-25fcc9602ed2.png)

**Comment by designlanguage** [comment]
Also, are there any other versions of the FFIEC logo? If it needs to be there, white on white with a drop shadow isn't ideal.

**Comment by lesgou** [comment]
I was able to find this: 
![image](https://cloud.githubusercontent.com/assets/9752096/26070117/4323c6a8-3958-11e7-98de-eb7d3e610552.png)

**Comment by designlanguage** [comment]
Thanks @lesgou !

Also, here are some thoughts on the logged out home page:
![screen shot 2017-05-15 at 1 39 41 pm](https://cloud.githubusercontent.com/assets/10562544/26070871/2c8336ba-3974-11e7-8833-750d0973a952.png)

**Comment by designlanguage** [comment]
@lesgou - Also found this one without a drop shadow. Not sure if we need an official image rather than one found through a search engine, but it'll probably do for now.
![ffiec-logo-wide](https://cloud.githubusercontent.com/assets/10562544/26076164/ca0ca586-3985-11e7-8f79-8cf05f4f28ff.png)

**Comment by lesgou** [comment]
:+1:

**Comment by designlanguage** [comment]
Wanted to throw this out there for our discussion later this morning.

Rather than showing steps on the side of the filing, what if they are part of the filing, also having the benefit of showing a filing's progress? We'd have to work on text and hierarchy, but the general idea could be something like this:

| Pre-upload | S&V edits | Q edits |
| --- | --- | --- |
| ![homepagea](https://cloud.githubusercontent.com/assets/10562544/26110746/36c1fef6-3a21-11e7-8e75-28d751d665e2.png) | ![homepageb](https://cloud.githubusercontent.com/assets/10562544/26110753/38e0339c-3a21-11e7-8dba-fff15d61f28c.png) | ![homepagec](https://cloud.githubusercontent.com/assets/10562544/26110748/36cb24a4-3a21-11e7-97a3-27723285e6b2.png) |

**Comment by designlanguage** [comment]
@awolfe76 @wpears @lesgou @keileyo 

Here's a bit more fidelity to these sketches (though they are definitely still sketches and don't accurately reflect the USDS web standards).

| Sketch | Description/notes |
| --- | --- |
| ![screen shot 2017-05-19 at 1 01 12 pm](https://cloud.githubusercontent.com/assets/10562544/26258754/13bcd3ca-3c94-11e7-9bd8-3ea02c60c3ab.png) | __Logged out page:__ We may want to add a bit more context back in, but I wanted to see how much we could remove or shift to where the issue arises. On this page the deadline is listed at the top and most resources are pushed to the footer. |
| ![screen shot 2017-05-19 at 12 57 56 pm](https://cloud.githubusercontent.com/assets/10562544/26258755/13c7dc7a-3c94-11e7-865c-b016b6728200.png) | __Initial logged in page:__ This page is also majorly stripped down. Again, we may want a bit more context for "Upload a file", but since this takes you to the upload page, more context could be provided there where it's more applicable. All other steps are viewable here, but grayed out. We can also discuss the wording of the steps. The note about additional institutions is added below the gray box here. |
| ![screen shot 2017-05-19 at 12 58 01 pm](https://cloud.githubusercontent.com/assets/10562544/26258758/13e6d436-3c94-11e7-8cc5-6f157926c50e.png) | __Syntactical & Validity Edits:__ Completed steps get a black checkmark. The previous uploads can be hidden in an expandable. The active step will be converted to a blue button. To keep the attention on the active step, "upload a new file" will sit beside it. There's also an opportunity to add more context to the step circles (here it's an exclamation point). |
| ![screen shot 2017-05-19 at 12 58 09 pm](https://cloud.githubusercontent.com/assets/10562544/26258757/13cf38ee-3c94-11e7-8007-df8454f8061a.png) | __Quality Edits:__ Text changes on the completed steps to accurately reflect the status. Again, a different minicon is used here to indicate the nature of the Quality Edits. |
| ![screen shot 2017-05-19 at 12 58 15 pm](https://cloud.githubusercontent.com/assets/10562544/26258756/13cb8f50-3c94-11e7-9e87-97a5570e3f81.png) | __Confirmed:__ Once the whole process is completed, having the upload link beside the completed confirmation indicates it's not final. |

**Comment by awolfe76** [comment]
#556 makes some changes to the institution page to help with accessibility, but it also seems to make the headings and status make more sense as well by grouping them a little better.

![institution](https://cloud.githubusercontent.com/assets/2932572/26375571/7fc18d4a-3fd7-11e7-90df-de096ab75d15.png)

I think that makes the current status pretty clear. We should schedule a few minutes to talk about it a bit more.

**Comment by designlanguage** [comment]
@awolfe76 - Yeah, happy to discuss this. How about 12:30?

**Comment by wpears** [comment]
@designlanguage I like the ideas here, especially the fat footer for all related links and the progress indicator on the institutions page. For the latter there are some implementation notes, but we can talk through some of this and figure out where we want to go.

**Comment by awolfe76** [comment]
Closing this one out. I think it's served its purpose. 😄 

See #567 - #573 and if I missed anything please create more.
