### ISSUE TITLE
Custom status desc for macro/quality

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#564]
Now that we rely on the API for the status description the message is a bit off for when syntactical/validity edits are ok but there are still macro/quality edits. The message says:

> The data validation process is complete, but there are edits that need to be addressed. The filing process may not proceed until the file has been corrected and reuploaded.

But, the

> The filing process may not proceed until the file has been corrected and reuploaded

isn't right. Quality/macro only need verification.

Add a custom message in this case.

**Comment by wpears** [comment]
This seems like more a problem with the API response than something we should work around on the front-end.

Also, this may be symptomatic of the fact that there doesn't exist a status code that differentiates syn/val edits from qual/macro, even though there is a great effect on the state of the application (one forces a refile, one doesn't). We've proxied this state through accessing the edits, but it's always been a problem specifically on the `/institutions` page, since we don't make a call to the edits endpoint to tease out whether syn/val exist or not.

Imo, the best solution would be introducing a new status code, ie `validated_with_errors` vs `validated_with_required_justification` or something. This issue would be solved by adjusting handling of the status codes and messages on the front-end to match such a structure.

Barring the addition of a status code, the API could just drop the second sentence (which makes the state more vague until they click through, but less incorrect).

Alternatively, we could forsake gods and men to call the edits endpoint on the institutions page **for every institution** to check edit counts and render a custom, more accurate message. I don't want to say this is HUGELY GROSS, but it certainly isn't too elegant, especially when we already have an endpoint with the intent of giving us insight into the state of the filing process.

**Comment by awolfe76** [comment]
> Imo, the best solution would be introducing a new status code, ie validated_with_errors vs validated_with_required_justification or something. This issue would be solved by adjusting handling of the status codes and messages on the front-end to match such a structure.

I agree, but we decided not to do this a while back.

> Barring the addition of a status code, the API could just drop the second sentence (which makes the state more vague until they click through, but less incorrect).

Yep, I agree. I'll create an issue over there. (https://github.com/cfpb/hmda-platform/issues/990)
