### ISSUE TITLE
Add progress to the institutions page

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#570]
For more details see from https://github.com/cfpb/hmda-platform-ui/issues/512#issuecomment-301798018 down but the idea is to show the steps and current progress from the institutions page.

@designlanguage - I'm going to close #512 and break it out into other issues. Once we have the idea down we can re-assign this for the implementation.

**Comment by designlanguage** [comment]
Here's a more fleshed out version of the sketch from the https://github.com/cfpb/hmda-platform-ui/issues/512#issuecomment-301798018. Looking forward to discussing this, but any feedback in the meantime would be great. 

| Image | Step & Notes |
| --- | --- |
| ![screen shot 2017-06-07 at 5 45 31 pm](https://user-images.githubusercontent.com/10562544/26903020-8fd1ca5a-4ba9-11e7-96ef-732d28b05cf1.png) | __1__. We can say "current filing period" instead of 2017. I'm wondering whether we should say "Upload your LAR file" or just remove LAR? |
| ![screen shot 2017-06-07 at 5 45 42 pm](https://user-images.githubusercontent.com/10562544/26903019-8fcf059a-4ba9-11e7-8508-de10537a432b.png) | __2__. Text for the steps change depending on status. Completed Step 1 becomes an expandable when there have been multiple uploads. For most of these steps, more descriptive text has been added, and the button is separate from the heading. |
| ![screen shot 2017-06-07 at 5 45 52 pm](https://user-images.githubusercontent.com/10562544/26903021-8fd49884-4ba9-11e7-9b2e-c02d765831fe.png) | __2.5__. Suggestion for revised text in the expandable: "View edit reports for your previous uploads". |
| ![screen shot 2017-06-07 at 5 45 59 pm](https://user-images.githubusercontent.com/10562544/26903022-8fd4bc6a-4ba9-11e7-951d-fadb8816cbc0.png) | __3__. Adjusted the language to be specific for when Quality edits are found.  |
| ![screen shot 2017-06-07 at 5 46 08 pm](https://user-images.githubusercontent.com/10562544/26903025-8fd8cb52-4ba9-11e7-9155-4020360bebbc.png) | __4__. Maybe we could also differentiate here when Quality/Macro Quality edits have been validated and when there are none. |
| ![screen shot 2017-06-07 at 5 46 16 pm](https://user-images.githubusercontent.com/10562544/26903024-8fd56be2-4ba9-11e7-9a27-9899001a0ad0.png) | __5__. Not sure about the language here. Any thoughts on this? |
| ![screen shot 2017-06-07 at 5 46 29 pm](https://user-images.githubusercontent.com/10562544/26903023-8fd54734-4ba9-11e7-94ca-530da83b644b.png) | __Completed__. Re-upload is still an option at this step. Maybe we want more of a visual indication that the process is done? |

**Comment by lesgou** [comment]
1. I would lean towards keeping the year, but this is more for future years, when they can go back and resubmit for previous years - to make sure that they are submitting for the correct year. 
a. "LAR" is not required to be there.
2. I wonder if having each file within each expandable field would be confusing. Is the goal to have a file under each stage? (if a filer has uploaded multiple files and each is at a different stage?)
2.5.  Wording looks good, but would that section be too long because we are also providing the "[state](https://github.com/cfpb/hmda-platform/blob/master/Documents/submission-status.md)" of that particular upload?
3. I think @awolfe76 has some [updated language](https://github.com/cfpb/hmda-platform/issues/990) for that 
4. Seems cool, the "edits found" vs. "edits validated"
5. Is this pulling from the [states](https://github.com/cfpb/hmda-platform/blob/master/Documents/submission-status.md)? Maybe just keep the first sentence? "Review the Institution Register Summary and Validation Summary"

**Completed**: I also think that we should use the word "resubmit" here instead of "restart" to indicate that the data have been submitted.

**Comment by designlanguage** [comment]
1. 👍  Makes sense. 
    a. I wonder if "LAR" would be helpful context, or just extraneous.
2. The uploaded filename would always be shown in step 1, regardless of which step you selected "upload a new file". I believe any of those links will send you back into the platform at step one, so keeping it there reflects what's happening. And if you're at step 4, and make adjustments to your file that accidentally create a syntactical edit, showing the file at step 4 would be strange if the file was at step two. My thought was to have only the recent upload would be shown as the expandable heading. Within the expandable would be downloadable edit reports for previous uploads. We can chat about this.
3. Ah okay, thanks. I wonder if a filer needs to know that data validation is complete in this step, or just that there are edits that need to be addressed.
4. 👍 
5. "Review Summary" doesn't sound like an essential step, and I want to make sure people don't think they're done and skip pressing the button. Pretty sure I pulled that second sentence from the description in step 5 (platform is down currently, so I can't check). If unnecessary, it can go.
6. 👍

**Comment by lesgou** [comment]
1a. Technically, you could say "upload your LAR", so maybe it could be removed?
3. I think if validation were complete, there would be a checkbox to depict this?
5. Maybe we should call it something else. This is a super important step because they have to sign and submit. (I'm not opposed to naming this "Super Important Step").

**Comment by designlanguage** [comment]
@lesgou - 
I was giving some further thought to keeping 2017 as a subheading for the institutions page.

Right now we're thinking of the page with institutions as the "institutions page", but that's because we only have a single year of data shown when this goes live. When we add multiple years, institutions are really the subcategory and filing period is the main category because all the "active" filings should be at the top of the page.

I've heard that filers might have some confusion about whether the "2017 filing period" refers to the year their filing in, or the year of the data. However we handle this heading should aim to minimize this. One option could be something like:
* __Filings for the current period (2017 data)__

Then after the institution(s) there, the next heading could say:
* __Filings from previous years__

**Comment by lesgou** [comment]
@designlanguage I agree.  We will definitely need consistent language throughout the platform. Where it can get tricky is with resubmissions, to make it clear that, for example, if it is the year 2020, and you resubmit 2017 data in 2019, you need to go back to the 2017 page, not 2019, even though the "previous year" when the resubmission happened was 2019.  (This is getting ahead a bit). So for now, how about:

**- Current filing period (data collected in 2017)**

(and then for future consideration):
**- Previous filing periods**

**Comment by keileyo** [comment]
We also need to make it clear that the platform will not have any "previous" filings before the filing period for data collected in 2017.

**Comment by designlanguage** [comment]
@lesgou - Sounds good!
@keileyo - Yes, we won't show that second heading when the platform is launched, I just want to make sure we have a plan going forward.

**Comment by keileyo** [comment]
@designlanguage cool! even when we do start thinking about it for 2018 filing period, we should probably make it clear. Thinking something like this:

For 2018:
**- Current filing period (data collected in 2018)**

**- Previous filing periods (2017)**

For 2019:
**- Current filing period (data collected in 2019)**

**- Previous filing periods (2017, 2018)**

etc etc

**Comment by designlanguage** [comment]
@keileyo I was thinking the previous years could be subheads. So the hierarchy would be:

## Current filing period (data collected in 2019)
* box
## Previous filing periods
#### Data collected in 2018
* box
#### Data collected in 2017
* box

**Comment by keileyo** [comment]
@designlanguage coolio :+1:

**Comment by awolfe76** [comment]
From the screenshots, are we suggesting that we removing the timing part from these? The part that says something like "Started 22 minutes ago". I'm ok with doing it, just want to be sure.

**Comment by lesgou** [comment]
I have no preference.

**Comment by designlanguage** [comment]
@awolfe76 @wpears @keileyo - would appreciate your thoughts on these:

Here's what I'm proposing to indicate steps in the institutions page.

By showing the steps horizontally, it's a better preview of what the platform looks like. It also allows them to be slightly disconnected from the description, which helps because steps 2-4 have to be grouped here.

I've also proposed some content changes below.

![screen shot 2017-10-04 at 1 25 44 pm](https://user-images.githubusercontent.com/10562544/31189937-a46b4f5c-a907-11e7-9a8d-d9afaa3943af.png)

### No data has been uploaded yet. 
Make sure your data is in a pipe-delimited text file.
__Upload your file__

![screen shot 2017-10-04 at 1 28 04 pm](https://user-images.githubusercontent.com/10562544/31190046-ec61dd26-a907-11e7-8e58-0f21cc5e5009.png)

### Your data has formatting errors.
Review these errors and update your file. Then, upload the corrected file.
__Review formatting errors__

![screen shot 2017-10-04 at 1 29 27 pm](https://user-images.githubusercontent.com/10562544/31190079-13433afc-a908-11e7-8cb9-6b95b8906c2f.png)

### Your data has edits that need to be addressed.
Your file has been uploaded, but the filing process may not proceed until edits have been 
verified or the file has been corrected and re-uploaded.
__Review edits__

![screen shot 2017-10-04 at 1 26 03 pm](https://user-images.githubusercontent.com/10562544/31189938-a4700074-a907-11e7-96ac-19ba1f9f209a.png)

### Your data is ready for submission.
Your financial institution has certified that the data is correct, but has not been submitted yet.
__Review summary__

![screen shot 2017-10-04 at 1 26 11 pm](https://user-images.githubusercontent.com/10562544/31189941-a476e880-a907-11e7-9700-522421193c92.png)

### Your data has been submitted.
This completes your HMDA filing process for this year. If you need to upload a new HMDA file, the previously completed filing will not be overridden until all edits have been cleared and verified, and the new file has been submitted.
__View completed filing__

**Comment by designlanguage** [comment]
An alternative would be to list the name of the file in these heading:

![screen shot 2017-10-04 at 1 44 35 pm](https://user-images.githubusercontent.com/10562544/31190832-491460a0-a90a-11e7-854e-b2d39e8bc2b7.png)
![screen shot 2017-10-04 at 1 44 44 pm](https://user-images.githubusercontent.com/10562544/31190831-4913debe-a90a-11e7-9de0-5e631652cb15.png)
![screen shot 2017-10-04 at 1 44 50 pm](https://user-images.githubusercontent.com/10562544/31190833-49188252-a90a-11e7-9877-ac0a123feedf.png)

**Comment by designlanguage** [comment]
In the second round of testing, participants expected to see the steps in the institution page.

Once they had been in the platform and navigated back to the home page, they wondered if the steps were shown in the history expandable.

Based on both rounds of testing, this is high on my priorities list.

**Comment by designlanguage** [comment]
@awolfe76 -

Because the institutions page has to show multiple steps at once (2, 3, 4), we will need to remove some detail from the nav. The various punctuation icons and colors might not be as helpful when viewed together. Removing different colors and keeping only numbers and check marks as icons will simplify the nav.

We also discussed removing the icon labels, but I believe they are necessary to prime the user about what will be addressed when in the platform. I do think the detail of the step labels can be simplified though, to just a before/after state, since the specific status is listed in the heading below.

| Before label | After label |
| --- | --- |
| Upload | Uploaded |
| Syntactical & validity edits | No syntactical or validity edits |
| Quality edits | Quality edits verified |
| Macro quality edits | Macro quality edits verified |
| Submission | Submitted |

#### Here's what the icons/labels could look like.
For an accepted submission, I like the idea of showing green in the institution somewhere. Previously it had been the status text. Here I have it as the button.


| Step | Current | Recommendation |
| --- | --- | --- |
| No upload |  | ![screen shot 2017-12-15 at 11 43 25 am](https://user-images.githubusercontent.com/10562544/34051796-de9abda2-e18d-11e7-9bed-1a5b3290c88b.png) |
| Formatting errors | ![screen shot 2017-12-15 at 9 35 40 am](https://user-images.githubusercontent.com/10562544/34051791-de5abc0c-e18d-11e7-906a-ecaf64c8467c.png) | ![screen shot 2017-12-15 at 11 43 32 am](https://user-images.githubusercontent.com/10562544/34051797-deaaa438-e18d-11e7-97f8-6d36ed842cd6.png) |
| Edits | ![screen shot 2017-12-15 at 9 36 45 am](https://user-images.githubusercontent.com/10562544/34051792-de67fd86-e18d-11e7-9adf-1747c9725a00.png) | ![screen shot 2017-12-15 at 11 43 40 am](https://user-images.githubusercontent.com/10562544/34051798-debc7f8c-e18d-11e7-94ee-4aef87a6f6d6.png) |
| Submission | ![screen shot 2017-12-15 at 9 37 37 am](https://user-images.githubusercontent.com/10562544/34051794-de77588a-e18d-11e7-82d9-e6f309436367.png) | ![screen shot 2017-12-15 at 11 43 51 am](https://user-images.githubusercontent.com/10562544/34051799-deccf9ca-e18d-11e7-84a1-3fa6c015dbfb.png) |
| Accepted | ![screen shot 2017-12-15 at 9 38 20 am](https://user-images.githubusercontent.com/10562544/34051795-de864ee4-e18d-11e7-8c6d-69388f9c485f.png) | ![screen shot 2017-12-15 at 12 10 39 pm](https://user-images.githubusercontent.com/10562544/34052670-4f6ac1c8-e191-11e7-87cb-a633b8281615.png) |
