### ISSUE TITLE
Improve upload/validation progress bar and messaging

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#642]
The progress bar could be improved, both visually and UX. 

Some things to think about (there could be others):
- positioning on the `%` on either side (are they even necessary in this case)
- positioning of the messaging for each stage
- the blinking blue dot
- should we show an additional % for the current progress, that moves along with the blue bar
  - could we show the messaging along with this
- we show all the steps in the submission process, should we do the same here

# In progress
![progress-in-progress](https://user-images.githubusercontent.com/2932572/27737805-814a19f8-5d77-11e7-9a72-9b914ea827f9.png)

# Complete
![progress](https://user-images.githubusercontent.com/2932572/27737811-87aa7536-5d77-11e7-90e4-5e5fe028a456.png)

**Comment by designlanguage** [comment]
Stepping back for a second, the main purpose of the progress bar is to indicate that the user's file is being uploaded... that something is happening. Some filers may have small uploads, but some will be very large and take a long time. If a filer's expectation isn't correctly set, it may result in a lot of calls/emails to HMDA help.

It's from that perspective that I want to look at these different elements.

#### The blue bar
I believe accurate progress can't be determined the way the platform is currently structured, so in a large file, the bar will hang in one location, possibly for minutes. This won't give the user confidence that something is happening.

#### Percentages
Right now these are acting as labels for the ends of the blue bar. It would be more helpful if there was one % displayed that was the current status of the file upload. Just like the blue bar though, this is a problem because if an accurate percentage can't be displayed, it will look like progress is frozen.

#### The blinking blue dot
The blue dot seems to be trying to reassure the user that even though the progress bar isn't moving, progress is still being made on their file. I don't think it's enough to convince a user that the platform is doing something after several minutes.

#### Listing steps
This is how the previous upload process was structured and I don't think it would solve the issue of notifying the user that progress is being made in the middle of a step in a large file. It would be seemingly idle at that point. I also think listing the steps is more information that a filer needs at this point. None of the steps are actionable for a user, and if they're not actionable, all the user needs to know at that point is that the file is uploading, and then that the file is uploaded.

#### Alternatives
So how can we indicate progress to a user? Can the platform be structured in a way that can return accurate progress in the upload process? If not, there are still alternatives. Can we show the expected time an upload will take based on the size of the file (or other measures like number of rows)?
If so, this could take the form of a countdown timer. It would help set the user's expectation about what is supposed to be happening.

**Comment by designlanguage** [comment]
@wpears @awolfe76 

I know this has some back end dependencies, but I wanted to document it here.

If we can determine approximations of how long an upload _might_ take, we could still use a progress bar. It doesn't need to be a totally accurate representation, just give the user a sense of progress and that something's happening.

For example, if we estimate a file will take 10 minutes to upload/parse/validate, and the breakdown of timing would be Upload: 30 secs / Parse: 3.5 mins / Validate: 6 mins, maybe we could still use a progress bar.

### Estimations

| Upload | Parsing | Validation |
| :---: | :---: | :---: |
| - 5% - | ------------- 35% ------------- | ------------------------ 60% ------------------------ |
| 30 s | 3.5 mins | 6 mins |

What if each segment shows progress in a half-life (moves halfway in half the amount of time estimated)?

For example, if validation is expected to take 6 minutes, it could proceed half way in 3 minutes, then 1/4 further in the next three minutes. Once it completes (early or late), it can proceed to the end of the segment quickly.

### Visible progress

| Validation |
| --- |
| l ----------------------- 60% ----------------------- l |
| l ------ 3 mins ---------- l --- 3 mins --- l 3 m l - l l |

The result would be that a user would have a _rough_ indication of progress, and they'd see the % moving to feel like something is happening.

Also, I don't think think the breakdown of upload/parsing/validation should be labeled for the user, but we can account for it in how progress is displayed.

Thoughts?

**Comment by awolfe76** [comment]
I like this idea a lot, but it does require some past history of uploads to be able to get a good idea of the timing.

I think we should think about any other improvements that we can make until then.

What if we give an indication of how long something has been running?

**Comment by wpears** [comment]
We could also put in a front-end only heuristic, we know the file length. Could just submit files of 10 different sizes, plot their time-to-validate, and end up with a rough mapping of file size to time-to-validate. Of course this will change with network, memory, and cluster conditions and would ultimately best be provided by the backend, but we could implement this in such a way that it would be a drop in replacement (ie an independent component that accepts a time estimate as a prop).

**Comment by awolfe76** [comment]
Seems ok to me, as long as we feel pretty confident on our estimations. To get the best estimates I'd think we'd need close to the full blown application running in the correct environment.

So if we go this route, we put this issue on the backlog and wait for the right setup.

Also still seems like we'd want some sort of timer there (approx x minutes remaining), or at least some idea of current % complete.

**Comment by designlanguage** [comment]
@wpears  @awolfe76 -

I like that idea of a preliminary estimate before receiving data from the back end. The main purpose is that the user sees an endpoint and they know they are getting closer to it, it doesn't have to be accurate.

To that end, I don't think we should list a time estimate before we have more data. We can wait, maybe throughout the beta period, before adding a timer that says something like "This process may take between 3-6 minutes," Or "Approximately 6 minutes remaining".

Instead, we'd just use our rough estimate to show a % completed in the progress bar. And even if it takes double the time we estimate, the user will be able to see that there's an endpoint and that progress is being made, even if the bar is moving a little slower than it was a minute ago.

**Comment by designlanguage** [comment]
This concern has proven out in tests so far. Can we add this to the beta release @wpears?

**Comment by awolfe76** [comment]
From conversation the other day ...

As a faster fix can add some messaging to say something like "You can log out and come back later"while leaving the progress bar as is? This message should only appear after the upload has completed.

Then later look into these improvements.
