### ISSUE TITLE
Wording for modals

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#675]
We have 2 modals. The design is consistent, but _I think_ the content could be better. Rather than the title for both being "HMDA Filing" the titles should be more about what the modal is doing. Something like "You have timed out." and "You are about to refile." and then have an appropriate message/description in the body along with the buttons.

The goal of this issue is to decide on both the titles and the body for both modals.

# Current modals

## Refile
![modal-refile](https://user-images.githubusercontent.com/2932572/28727563-4e3e90de-7393-11e7-8e8d-12954584d3db.png)

## Timeout
![modal-timeout](https://user-images.githubusercontent.com/2932572/28727570-535b8d1a-7393-11e7-847c-f471c82a8461.png)

**Comment by lesgou** [comment]
How about:
For Refile:
Title: Begin Resubmission Process
Content: Are you sure you would like to begin the resubmission process?
Button: Yes, begin the resubmission process.


For Timeout:
Title: Session Timed Out
Content: Your session has time out, but your work has been saved. Please log in again.

@keileyo @designlanguage thoughts?

**Comment by designlanguage** [comment]
@lesgou - For timeout, I would add an alternative, whether it's an "x" in the modal or a "stay logged out" link. The only other thing I'd add is in the content: "Your session has timed out, but your work has been saved. *To continue*, please log in again."

For refiling after submission, I wonder if changing the name of the process ("restart filing" to "begin resubmission") is enough to indicate that the last submission won't be replaced until the process is complete. I think content in the institutions box will be needed clarify that.

Will the resubmission modal only pop up if the last thing they did was submit their file? If they're in the middle of resubmitting, and upload a new file, "begin resubmission" might not seem accurate because they've already begun.

**Comment by lesgou** [comment]
I agree on both, @awolfe76 , does the resubmission modal only appear after the submission has been signed? Or is this modal used in all situations when a new file is going to be updated?

**Comment by keileyo** [comment]
@lesgou @designlanguage @awolfe76  it is for all situations where a new file is going to be updated.

**Comment by lesgou** [comment]
In that case, I would prefer not saying "Begin Resubmission" because what if the filer hasn't even submitted yet the first time?

**Comment by designlanguage** [comment]
From a filer's standpoint, they aren't really restarting the filing process by uploading a new file. Going back and fixing a file and re-uploading is all part of the process for them, even though some of it happens outside of the platform.

Interested to know your thoughts, @keileyo and @lesgou.

How about we say something like:

### Upload a new file?
__Are you sure you want to replace your HMDA data for this filing?__

**Comment by lesgou** [comment]
:+1:
