### ISSUE TITLE
In pagination, location sometimes jumps

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#698]
Clicking "next" on a paginated table sometimes jumps you to the bottom of the page. This behavior has been captured in a couple user tests, if it isn't easily replicable.

**Comment by wpears** [comment]
Yeah, this will occur when paging to the last page which has fewer than 20 records. It happens because the layout of the whole page is dependent on the space the tables fill. There are a couple workarounds /approaches to making this feel more natural:
  - 1. reduce padding on table rows so jumping is less confusing
  - 2. always jump to the top of the table
  - 3. calculate where the pagination component will end up and jump there so the buttons are in the same spot
 - 4. some combination of 1 & 3 or 1 & 2

**Comment by designlanguage** [comment]
How about a combination of 1, 3, and 5?

- 5. Decrease the maximum visible table rows to 10 (or 15). Basically an amount that is reasonably likely to appear on a screen in its entirety?
