### ISSUE TITLE
Language in upload box after file is uploaded

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#780]
![screen shot 2017-09-18 at 11 21 41 am](https://user-images.githubusercontent.com/10562544/30550258-e5243cf2-9c64-11e7-867b-c4a4c8accfd4.png)

The text in the upload box says the submission is in progress when it's done and also when it's hit an error. 

* I think we should change "submission" to "upload", especially because filers have shown they are used to a one-and-done process.

* Can the text also be made custom for each outcome? "Upload of __filename.txt__ is ready for review." and "__filename.txt__  has formatting errors."

@keileyo @awolfe76 @wpears

**Comment by wpears** [comment]
So "submission" here means the whole submission process, the upload, then edit verification etc. which is why it displays like it does. If you sign the submission and return to this page, you'll see that it will display as "complete".

That said, I think since this component handles the upload, we should be more explicit in the outcome (your second bullet). PR to come.
