### ISSUE TITLE
Upgrade to React 16.0

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#792]
~~### This will require a CR.~~

React recently [released 16.0](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html). This will allow us to do some refactoring because we can [return fragments and strings](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings) but perhaps, more importantly, it will [reduce the bundle size](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html#reduced-file-size).

**Comment by wpears** [comment]
This isn't going to be turnkey, there are all sorts of fun complications.
 - redux-oidc has to be upgraded due to its internal use of React.PropTypes, and v3 has a different API
 - react-router will need to be upgraded, probably okay to use 3.2 rather than doing the whole v4 upgrade now (which is a complete rewrite with a completely different API)
 - it seems like rendering conditions are different under certain circumstances, (to wit, the `<Edits/>` container isn't getting rerendered on navigation)

I have work doing all of the above in a branch, but going to back-burner it for now as I'm not super interested in working through any issues that crop up here right when we step into beta.

**Comment by awolfe76** [comment]
Bummer ☹️ but I agree. We can get back to this later.

Do you get an idea of a possible smooth path forward? Like

- upgrade this
- upgrade this
- now we can upgrade react
- upgrade this

Just thinking about being able to split work (and PRs) to make it simple, but realize that just might not be that lucky.

**Comment by wpears** [comment]
Possibly, the problem is there are things with peer dependencies on React 16 vs 15. Still, I think it's likely we can do smaller changes, but we'll see. The main trouble seems solely with React 16 itself shortcircuiting a child's needed render, but I'll look into it more,
