### ISSUE TITLE
Sessions and queries

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#8]
Is the data flow one directional or bi-directional? Before submitting anything (but after authenticating) does a user see information about what they have submitted previously? Or does a user just submit a file again and hope everything works out?

Should we be focused on making multiple submissions as easy as possible? Opt-in early submission both increases data quality and decreases time to publication... should we design the system with this in mind?

**Comment by awolfe76** [comment]
The idea is that users would be able to see information about a previous submission given that it reached a certain point ... uploaded, parsed, valid syntax, etc. So they would be able to see previous errors but they would have to re-upload the entire file in order to correct errors in a previous submission.

**Comment by wpears** [comment]
So front-end/back-end interaction goes like this:

Log in -> hit API authorization endpoint
Get current app state -> retrieve user's most recent submission
Render front-end based on app state

**Comment by awolfe76** [comment]
:+1: That's the way I see it too, with some interactions to "save and continue" during the process. Or to save a justification in quality and macro.

But at the initial load, yeah, that's it.

**Comment by wpears** [comment]
Auth stuff will be largely governed by our auth solution; other solutions have been incorporated. Closing
