### ISSUE TITLE
Remove beta content

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#935]
Go through the app and update content to remove all references to beta.

**Comment by designlanguage** [comment]
@keileyo @colleenms - let me know what you think about these changes for the submission page:


__Your filing is ready to be signed and submitted__
Please review your HMDA Filing Summary and sign your filing at the bottom of this page.
If you discover an error in the summary, you will need to update your file and upload it again.

### Signature

To sign your submission, select the checkbox below. Next, select the "Submit HMDA data" button to complete your filing.
- [ ] I am an authorized representative of my institution with knowledge of the data submitted and am certifying to the accuracy and completeness of the data submitted.

__Submit HMDA data__

**Comment by colleenms** [comment]
@designlanguage Looks good. Only suggestion is to change "If you discover an error in the summary" to "If you discover an error in your summary."

"The filing period is closed." banner should be replaced with the "The filing period is open." banner since the filing period will be open when the site is launched. We can change it back to the closed message after April 1.

![image](https://user-images.githubusercontent.com/32906749/33962869-f7802492-e020-11e7-898f-c8d7c52df566.png)

**Comment by awolfe76** [comment]
Thanks, @colleenms. [This](https://github.com/cfpb/hmda-platform-ui/issues/935#issuecomment-351528131) will happen automatically. We change the alert in this case based on the date.

**Comment by keileyo** [comment]
@awolfe76 @designlanguage 

The submission page language was carefully crafted w/ Legal and cleared by all parties.  Please revert the signature text to:

### Signature

To complete your submission, select the checkbox to certify the accuracy and completeness of the data submitted. Next, select the “Submit HMDA data” button to submit your data.

- [ ]  I am an authorized representative of my institution with knowledge of the data submitted and am certifying to the accuracy and completeness of the data submitted.
