### ISSUE TITLE
Remove warning from signature component?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#990]
Do we need this anymore? They can't get here until edits have passed anyway. I suspect this has been lingering here for a while, from an old way of handling it.

https://github.com/cfpb/hmda-platform-ui/blob/f4c2c9e816d873b3d013526b6c5f868a118c194c/src/submission/signature/index.jsx#L16-L35

**Comment by wpears** [comment]
This is about actual errors, not edits, so like if there was an HTTP error retrieving the irs report (which is why this code was originally inserted). So this is still valid in that use case.

**Comment by awolfe76** [comment]
You're right, part of it is needed, but that ~~second~~ third return is talking about edits.

Couldn't we remove that and clean up the first `if` statement? I don't think we need the status code check there.

**Comment by wpears** [comment]
Ah, duh, a scroll bar.

Yeah it's true that the router shouldn't allow this page to be visited when edits exist, so that can be taken out.

IIRC, it was added for an abundance of caution after some buggy state allowed visiting the page while requests were still in flight. The router has since been improved so this is no longer an issue.

**Comment by awolfe76** [comment]
Yeah, [check this out](https://github.com/cfpb/hmda-platform-ui/commit/0145e7d78a55255a1858535998348061d1794fc7). I think that's when we introduced this, to prevent/warn that they can't sign until all things are verified, including IRS. 😃 

So that was a long time ago!
